### ISSUE TITLE
Q on time-to-live

### ISSUE THREAD

**Issue by mhaberler** [KEGustafsson/signalk-net-ais-plugin#20]
Hello Karl-Erik,

I took your plugin and based https://github.com/mhaberler/signalk-net-adsb-plugin on it - same trick, different vessel

what is not clear to me: how are old vessel entries aged out? 

I do not see a mechanism in the signalK spec or your code

do they just live until reboot, and the UI's deal with the issue?

best regards

Michael

**Comment by KEGustafsson** [comment]
Hi Michael,

There is non due to SK has a build in functionality to remove inactive vessels.
Setting can be found from: 
`Server -> Settings -> Server Settings -> Maximum age of inactive vessels' data`
Set there value in minutes and if no updates in that time frame then SK remove vessel away.

**Comment by mhaberler** [comment]
perfect - thanks a lot!
